按照修改意见完善
fireinice/xiaoxin pull request #11
Opened 2024-12-21 11:08 UTC by 3xiaoli33

2024-12-21 15:44 UTC, fireinice requested changes

2024-12-21 15:44 UTC, fireinice commented on src/models/MetricsLoss_Model.py
这个文件没有删掉

2024-12-21 15:44 UTC, fireinice commented on src/models/Bacteria_morgan_model.py
> +import pandas as pd
文件名不要大写

2024-12-21 15:44 UTC, fireinice commented on src/models/Bacteria_morgan_model.py
> +        self.cross_attn = nn.MultiheadAttention(
这里不要叫cross_attn，引起误解

2024-12-21 15:44 UTC, fireinice commented on src/datamodule/Bacteria_Predict_datamodule.py
> +import logging
文件名不要大写

2024-12-21 15:44 UTC, fireinice commented on src/datamodule/Bacteria_Predict_datamodule.py
> +class BacteriaPredictDataModule(BacteriaDataModule):
这个类应该和BacteriaDataModule合并

2024-12-22 06:34 UTC, 3xiaoli33 commented on src/datamodule/Bacteria_Predict_datamodule.py
> +class BacteriaPredictDataModule(BacteriaDataModule):
合并的话  load_data函数和setup函数有些区别 是否可以不合并

2025-01-03 09:30 UTC, merged